import JotaiProvider from "@/components/JotaiProvider";
import Header from "@/components/layouts/Header";
import NextAuthProvider from "@/components/NextAuthProvider";
import { ToastProvider } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CustomContainer from "../components/CustomContainer";
import MantineProviderWrapper from "../components/MantineProvider";
import TanStackProvider from "../components/TanStackProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <JotaiProvider>
            <TanStackProvider>
              <MantineProviderWrapper>
                <ToastProvider>
                  <Header />
                  <CustomContainer>{children}</CustomContainer>
                  <Toaster />
                </ToastProvider>
              </MantineProviderWrapper>
            </TanStackProvider>
          </JotaiProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
