import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/app/components/NextAuthProvider";
import { Suspense } from "react";
import UserProfile from "@/app/components/UserProfile";
import JotaiProvider from "@/app/components/JotaiProvider";
import TanStackProvider from "./components/TanStackProvider";
import "@mantine/core/styles.css";
import MantineProviderWrapper from "./components/MantineProvider";
import { Inter as FontSans } from "next/font/google";
import Header from "@/app/components/layouts/Header";
import { ToastProvider } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";
import CustomContainer from "./components/CustomContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <JotaiProvider>
            <TanStackProvider>
              <MantineProviderWrapper>
                <ToastProvider>
                  <Header />
                  <CustomContainer>
                    <Suspense fallback={<div>loading...</div>}>
                      {children}
                    </Suspense>
                  </CustomContainer>
                  <Toaster />
                </ToastProvider>
              </MantineProviderWrapper>
            </TanStackProvider>
          </JotaiProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
